openapi: 3.0.3
info:
  title: Oversize Project API
  version: 1.0.0
  description: Oversize auth

servers:
  - url: http://localhost:4000

paths:
  /api/auth/register:
    post:
      summary: Foydalanuvchini ro'yxatdan o'tkazish (email orqali)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                firstname:
                  type: string
                  example: "To'lqinxon"
                lastname:
                  type: string
                  example: "Soliyev"
                phone_number:
                  type: string
                  example: "123"
                email:
                  type: string
                  example: "ashokhruzbek@gmail.com"
                password:
                  type: string
                  example: "1111"
              required:
                - firstname
                - lastname
                - phone_number
                - email
                - password
      responses:
        '201':
          description: Muvaffaqiyatli ro'yxatdan o'tkazildi
        '400':
          description: Xatolik yuz berdi

  /api/auth/send-otp:
    post:
      summary: Email orqali OTP kod jo'natish
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "ashokhruzbek@gmail.com"
              required:
                - email
      responses:
        '200':
          description: OTP yuborildi
        '400':
          description: Email noto'g'ri yoki yuborib bo'lmadi

  /api/auth/verify-otp:
    post:
      summary: OTP ni tekshirish va emailni tasdiqlash
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "ashokhruzbek@gmail.com"
                code:
                  type: string
                  example: "123456"
              required:
                - email
                - code
      responses:
        '200':
          description: Email tasdiqlandi
        '400':
          description: Xato kod yoki email

  /api/auth/sign-in/google:
    get:
      summary: Google orqali tizimga kirish
      tags:
        - Auth
      responses:
        '302':
          description: Google OAuth sahifasiga yo'naltirish

  /api/auth:
    get:
      summary: Barcha foydalanuvchilar ro'yxatini olish
      tags:
        - Auth
      responses:
        '200':
          description: Foydalanuvchilar ro'yxati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstname:
          type: string
          example: "To'lqinxon"
        lastname:
          type: string
          example: "Soliyev"
        email:
          type: string
          example: "ashokhruzbek@gmail.com"
        phone_number:
          type: string
          example: "+998901234567"
        role:
          type: string
          example: "user"
        image_url:
          type: string
          example: "https://example.com/profile.jpg"
